# Generated by Django 5.1.1 on 2024-11-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='carrito_items',
        ),
        migrations.AddField(
            model_name='venta',
            name='carrito_items',
            field=models.ManyToManyField(to='reserva.carrito'),
        ),
    ]
