# Generated by Django 5.1.3 on 2024-11-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0002_remove_venta_carrito_items_venta_carrito_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='precio',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
