# Generated by Django 5.1.3 on 2024-11-25 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0003_alter_carrito_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='tipodePago',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reserva.tipodepago'),
        ),
    ]
